### PR TITLE
Gatsby v2

### PR DESCRIPTION
**Pull request by spences10**
Various changes to move to Gatsby v2

- Remove the layout folder and page and change to component Layout
- Use `actions` in place of `boundActionCreators`

### CODE REVIEW

**Comment by JeanSebTr** [comment]
@spences10 thanks for the PR and sorry for the delay, I'll try to review it this week :)

**Comment by spences10** [comment]
Np @JeanSebTr, you want me to add you as a reviewer?

**Comment by spences10** [comment]
@JeanSebTr updated dependencies and fixed vulnerabilities.

**Comment by thatfrankdev** [comment]
Thanks for the contribution @spences10, we very much appreciate it! 👍

**Pull request merged**
